In [3]:
import zipfile
zipped = zipfile.ZipFile('/content/fma_metadata.zip', 'r')
zipped.extractall('/content')
zipped.close()

In [4]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Activation, Dropout
import numpy as np
import os
import IPython.display as ipd
import matplotlib.pyplot as plt 
import seaborn as sns

# Importing pandas library
import pandas as pd

In [5]:
tracks = pd.read_csv('fma_metadata/tracks.csv',index_col=0,header=[0,1])
features = pd.read_csv('fma_metadata/features.csv',index_col=0,header=[0,1,2])
#echonest = pd.read_csv('fma_metadata/echonest.csv')
#genres = pd.read_csv('fma_metadata/genres.csv')

In [ ]:
features

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
track_id
2             7.180653  5.230309  0.249321  1.347620  1.482478  0.531371
3             1.888963  0.760539  0.345297  2.295201  1.654031  0.067592
5             0.527563 -0.077654 -0.279610  0.685883  1.937570  0.880839
10            3.702245 -0.291193  2.196742 -0.234449  1.367364  0.998411
20           -0.193837 -0.198527  0.201546  0.258556  0.775204  0.084794
...                ...       ...       ...       ...       ...       ...
155316       -0.490129  0.463834  2.321970 -0.084352  1.662914  2.115189
155317       -0.461559 -0.229601 -0.496632 -0.422033  0.130612 -0.263825
155318        0.552473 -0.110498 -0.532014  0.263131 -0.224011 -0.530972
155319       -0.176901  0.187208 -0.050664  0.368843  0.066005 -0.857354
155320        0.489665  1.862421  0.854461 -0.103666 -0.249835  0.360283

feature                                             ...   tonnetz            \
statistics                                          ...       std
number            07        08        09        10  ...        04        05
track_id                                            ...
2           1.481593  2.691455  0.866868  1.341231  ...  0.054125  0.012226
3           1.366848  1.054094  0.108103  0.619185  ...  0.063831  0.014212
5          -0.923192 -0.927232  0.666617  1.038546  ...  0.040730  0.012691
10          1.770694  1.604566  0.521217  1.982386  ...  0.074358  0.017952
20         -0.289294 -0.816410  0.043851 -0.804761  ...  0.095003  0.022492
...              ...       ...       ...       ...  ...       ...       ...
155316     -0.237794  5.695442  0.830353  1.951819  ...  0.128410  0.022547
155317     -0.628103 -0.082687 -0.229483 -0.492753  ...  0.132964  0.023548
155318      1.713526  1.418444  1.325197  0.120333  ...  0.108324  0.017540
155319     -0.780860  0.626281 -0.630938 -0.787229  ...  0.088311  0.018328
155320     -0.366701  0.033578 -0.834606 -1.154845  ...  0.091421  0.020312

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
track_id
2           0.012111   5.758890  0.459473  0.085629  0.071289  0.000000
3           0.017740   2.824694  0.466309  0.084578  0.063965  0.000000
5           0.014759   6.808415  0.375000  0.053114  0.041504  0.000000
10          0.013921  21.434212  0.452148  0.077515  0.071777  0.000000
20          0.021355  16.669037  0.469727  0.047225  0.040039  0.000977
...              ...        ...       ...       ...       ...       ...
155316      0.019816   4.448255  0.172852  0.028773  0.028320  0.003906
155317      0.026527   3.270612  0.196289  0.031116  0.027832  0.002441
155318      0.020471   2.356727  0.212891  0.038450  0.037109  0.003418
155319      0.017936   6.188604  0.167480  0.041480  0.038086  0.004883
155320      0.016794  21.756050  0.845215  0.075141  0.044434  0.004395

feature
statistics      skew       std
number            01        01
track_id
2           2.089872  0.061448
3           1.716724  0.069330
5           2.193303  0.044861
10          3.542325  0.040800
20          3.189831  0.030993
...              ...       ...
155316      0.955388  0.012385
155317      1.283060  0.019059
155318      0.828569  0.017904
155319      1.818740  0.020133
155320      4.687204  0.137205

[106574 rows x 518 columns]

In [ ]:
tracks

            album                                                     \
         comments         date_created        date_released engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN
...           ...                  ...                  ...      ...
155316          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155317          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155318          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155319          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155320          0  2017-03-26 16:22:18  2017-03-26 00:00:00      NaN

                                                                              \
         favorites     id                                        information
track_id
2                4      1                                            <p></p>
3                4      1                                            <p></p>
5                4      1                                            <p></p>
10               4      6                                                NaN
20               2      4          <p> "spiritual songs" from Nicky Cook</p>
...            ...    ...                                                ...
155316           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155317           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155318           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155319           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155320           1  22906                                                NaN

                               \
         listens     producer
track_id
2           6073          NaN
3           6073          NaN
5           6073          NaN
10         47632          NaN
20          2710          NaN
...          ...          ...
155316      1506  Monty Hall
155317      1506  Monty Hall
155318      1506  Monty Hall
155319      1506  Monty Hall
155320      7481          NaN

                                                             ...       track  \
                                                       tags  ... information
track_id                                                     ...
2                                                        []  ...         NaN
3                                                        []  ...         NaN
5                                                        []  ...         NaN
10                                                       []  ...         NaN
20                                                       []  ...         NaN
...                                                     ...  ...         ...
155316                                                   []  ...         NaN
155317                                                   []  ...         NaN
155318                                                   []  ...         NaN
155319                                                   []  ...         NaN
155320    ['ballad', 'epic', 'rockabilly', 'curse', 'hex...  ...         NaN

                                 \
         interest language_code
track_id
2            4656            en
3            1470            en
5            1933            en
10          54881            en
20            978            en
...           ...           ...
155316        122           NaN
155317        194           NaN
155318        214           NaN
155319        336           NaN
155320        972           NaN

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN
...                                                     ...     ...      ...
155316    Creative Commons Attribution-NonCommercial-NoD...     102      NaN
155317    Creative Commons Attribution-NonCommercial-NoD...     165      NaN
155318    Creative Commons Attribution-NonCommercial-NoD...     168      NaN
155319    Creative Commons Attribution-NonCommercial-NoD...     294      NaN
155320                            Attribution-NonCommercial     705      NaN

                                                                              \
         number publisher                                               tags
track_id
2             3       NaN                                                 []
3             4       NaN                                                 []
5             6       NaN                                                 []
10            1       NaN                                                 []
20            3       NaN                                                 []
...         ...       ...                                                ...
155316        3       NaN                                                 []
155317        4       NaN                                                 []
155318        6       NaN                                                 []
155319        5       NaN                                                 []
155320        7       NaN  ['ballad', 'epic', 'rockabilly', 'curse', 'hex...


                                              title
track_id
2                                              Food
3                                      Electric Ave
5                                        This World
10                                          Freeway
20                                  Spiritual Level
...                                             ...
155316                                    The Auger
155317                              Let's Skin Ruby
155318           My House Smells Like Kim Deal/Pulp
155319                      The Man With Two Mouths
155320    Another Trick Up My Sleeve (Instrumental)

[106574 rows x 52 columns]

In [ ]:
track_ids = tracks.index.tolist()
data_track = tracks.loc[track_ids]
feature_ids = features.index.tolist()
data_features = features.loc[feature_ids]

In [ ]:
data_track

            album                                                     \
         comments         date_created        date_released engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN
...           ...                  ...                  ...      ...
155316          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155317          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155318          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155319          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155320          0  2017-03-26 16:22:18  2017-03-26 00:00:00      NaN

                                                                              \
         favorites     id                                        information
track_id
2                4      1                                            <p></p>
3                4      1                                            <p></p>
5                4      1                                            <p></p>
10               4      6                                                NaN
20               2      4          <p> "spiritual songs" from Nicky Cook</p>
...            ...    ...                                                ...
155316           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155317           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155318           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155319           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155320           1  22906                                                NaN

                               \
         listens     producer
track_id
2           6073          NaN
3           6073          NaN
5           6073          NaN
10         47632          NaN
20          2710          NaN
...          ...          ...
155316      1506  Monty Hall
155317      1506  Monty Hall
155318      1506  Monty Hall
155319      1506  Monty Hall
155320      7481          NaN

                                                             ...       track  \
                                                       tags  ... information
track_id                                                     ...
2                                                        []  ...         NaN
3                                                        []  ...         NaN
5                                                        []  ...         NaN
10                                                       []  ...         NaN
20                                                       []  ...         NaN
...                                                     ...  ...         ...
155316                                                   []  ...         NaN
155317                                                   []  ...         NaN
155318                                                   []  ...         NaN
155319                                                   []  ...         NaN
155320    ['ballad', 'epic', 'rockabilly', 'curse', 'hex...  ...         NaN

                                 \
         interest language_code
track_id
2            4656            en
3            1470            en
5            1933            en
10          54881            en
20            978            en
...           ...           ...
155316        122           NaN
155317        194           NaN
155318        214           NaN
155319        336           NaN
155320        972           NaN

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN
...                                                     ...     ...      ...
155316    Creative Commons Attribution-NonCommercial-NoD...     102      NaN
155317    Creative Commons Attribution-NonCommercial-NoD...     165      NaN
155318    Creative Commons Attribution-NonCommercial-NoD...     168      NaN
155319    Creative Commons Attribution-NonCommercial-NoD...     294      NaN
155320                            Attribution-NonCommercial     705      NaN

                                                                              \
         number publisher                                               tags
track_id
2             3       NaN                                                 []
3             4       NaN                                                 []
5             6       NaN                                                 []
10            1       NaN                                                 []
20            3       NaN                                                 []
...         ...       ...                                                ...
155316        3       NaN                                                 []
155317        4       NaN                                                 []
155318        6       NaN                                                 []
155319        5       NaN                                                 []
155320        7       NaN  ['ballad', 'epic', 'rockabilly', 'curse', 'hex...


                                              title
track_id
2                                              Food
3                                      Electric Ave
5                                        This World
10                                          Freeway
20                                  Spiritual Level
...                                             ...
155316                                    The Auger
155317                              Let's Skin Ruby
155318           My House Smells Like Kim Deal/Pulp
155319                      The Man With Two Mouths
155320    Another Trick Up My Sleeve (Instrumental)

[106574 rows x 52 columns]

In [29]:
hitlist = pd.concat([tracks['track'][['listens']], features['mfcc']], axis=1)
hitlist_temp = pd.concat([tracks['track'][['genre_top','listens']], features['mfcc']], axis=1)
grouped_hitlist = hitlist_temp.groupby('genre_top')
grouped_hitlist.get_group('Rock')
hitlist

,listens,"(kurtosis, 01)","(kurtosis, 02)","(kurtosis, 03)","(kurtosis, 04)","(kurtosis, 05)","(kurtosis, 06)","(kurtosis, 07)","(kurtosis, 08)","(kurtosis, 09)",...,"(std, 11)","(std, 12)","(std, 13)","(std, 14)","(std, 15)","(std, 16)","(std, 17)","(std, 18)","(std, 19)","(std, 20)"
track_id,,,,,,,,,,,,,,,,,,,,,
2,1293,3.856789,1.541901,0.000816,0.330728,0.118731,-0.342687,-0.259252,0.146735,0.410656,...,10.059609,8.601942,9.284250,9.245516,8.520863,8.560472,7.651871,7.246555,7.077188,7.391859
3,514,4.296755,1.399977,0.112535,-0.211170,0.032953,-0.023489,0.150404,0.046454,0.033484,...,8.771966,10.026867,6.978541,7.650417,9.600357,7.222888,8.398293,7.285423,7.417791,8.777440
5,1151,2.624517,2.415293,0.440233,-0.782131,-0.771069,-0.724216,0.090260,0.152119,0.261731,...,8.863638,9.581952,8.895723,8.141456,8.201844,7.780963,7.132692,7.539753,8.452527,7.334442
10,50135,5.076893,1.161854,2.095651,1.372743,-0.203574,-0.345354,-0.529139,0.561974,0.281350,...,8.289734,7.985110,7.075400,6.972649,7.071393,7.270959,7.051070,6.928591,6.430473,6.186294
20,361,11.880132,4.085320,0.002655,1.518562,0.181947,0.339014,0.367611,0.069932,-0.016032,...,7.706648,6.498904,6.845514,6.934421,7.019398,6.983841,6.813648,7.520811,7.098001,7.032246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155316,102,4.895152,5.361988,3.186483,0.510951,-0.143080,0.342237,0.771449,-0.184232,0.143237,...,7.401937,6.629143,5.860062,6.230947,5.923375,5.586200,5.516872,5.755764,5.105072,5.019556
155317,165,0.040857,1.752112,0.442188,-0.380960,-0.739809,-0.023362,0.264786,0.072084,0.295485,...,6.734644,6.955739,6.662989,6.478699,6.019901,5.757353,5.280114,5.674062,5.541949,5.266131
155318,168,0.581889,-0.129386,0.662489,1.025676,0.170532,1.827692,-0.189439,1.141878,0.022045,...,7.061307,6.943147,6.522048,6.780707,6.311563,5.789986,5.466107,5.607614,5.685448,5.449005
155319,294,5.164501,3.716359,2.881116,3.273014,0.707058,1.951918,-0.151555,0.230036,-0.327132,...,7.300332,5.971618,6.355647,5.602213,5.887583,5.110033,5.407447,5.317993,5.187994,5.260817
155320,705,4.619462,1.234909,1.236056,0.335577,0.009484,1.682914,0.317069,-0.128262,0.076033,...,7.538454,7.840639,6.794503,6.431658,6.400701,6.733516,5.603289,5.868379,6.128483,5.550875

In [30]:
# a = hitlist['listens'].unique()
print(hitlist['listens'].quantile(0.9))
hitlist['listens'] = np.where(hitlist['listens'] >= 4866, "Yes", "No")
hitlist

4866.0

,listens,"(kurtosis, 01)","(kurtosis, 02)","(kurtosis, 03)","(kurtosis, 04)","(kurtosis, 05)","(kurtosis, 06)","(kurtosis, 07)","(kurtosis, 08)","(kurtosis, 09)",...,"(std, 11)","(std, 12)","(std, 13)","(std, 14)","(std, 15)","(std, 16)","(std, 17)","(std, 18)","(std, 19)","(std, 20)"
track_id,,,,,,,,,,,,,,,,,,,,,
2,No,3.856789,1.541901,0.000816,0.330728,0.118731,-0.342687,-0.259252,0.146735,0.410656,...,10.059609,8.601942,9.284250,9.245516,8.520863,8.560472,7.651871,7.246555,7.077188,7.391859
3,No,4.296755,1.399977,0.112535,-0.211170,0.032953,-0.023489,0.150404,0.046454,0.033484,...,8.771966,10.026867,6.978541,7.650417,9.600357,7.222888,8.398293,7.285423,7.417791,8.777440
5,No,2.624517,2.415293,0.440233,-0.782131,-0.771069,-0.724216,0.090260,0.152119,0.261731,...,8.863638,9.581952,8.895723,8.141456,8.201844,7.780963,7.132692,7.539753,8.452527,7.334442
10,Yes,5.076893,1.161854,2.095651,1.372743,-0.203574,-0.345354,-0.529139,0.561974,0.281350,...,8.289734,7.985110,7.075400,6.972649,7.071393,7.270959,7.051070,6.928591,6.430473,6.186294
20,No,11.880132,4.085320,0.002655,1.518562,0.181947,0.339014,0.367611,0.069932,-0.016032,...,7.706648,6.498904,6.845514,6.934421,7.019398,6.983841,6.813648,7.520811,7.098001,7.032246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155316,No,4.895152,5.361988,3.186483,0.510951,-0.143080,0.342237,0.771449,-0.184232,0.143237,...,7.401937,6.629143,5.860062,6.230947,5.923375,5.586200,5.516872,5.755764,5.105072,5.019556
155317,No,0.040857,1.752112,0.442188,-0.380960,-0.739809,-0.023362,0.264786,0.072084,0.295485,...,6.734644,6.955739,6.662989,6.478699,6.019901,5.757353,5.280114,5.674062,5.541949,5.266131
155318,No,0.581889,-0.129386,0.662489,1.025676,0.170532,1.827692,-0.189439,1.141878,0.022045,...,7.061307,6.943147,6.522048,6.780707,6.311563,5.789986,5.466107,5.607614,5.685448,5.449005
155319,No,5.164501,3.716359,2.881116,3.273014,0.707058,1.951918,-0.151555,0.230036,-0.327132,...,7.300332,5.971618,6.355647,5.602213,5.887583,5.110033,5.407447,5.317993,5.187994,5.260817
155320,No,4.619462,1.234909,1.236056,0.335577,0.009484,1.682914,0.317069,-0.128262,0.076033,...,7.538454,7.840639,6.794503,6.431658,6.400701,6.733516,5.603289,5.868379,6.128483,5.550875

In [31]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import plot_tree, plot_importance

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE

In [32]:
Y=hitlist.loc[:,'listens']

X=hitlist.loc[:,hitlist.columns!='listens']
X.columns = [x[1] for x in X.columns]

cols=X.columns

scaler=preprocessing.MinMaxScaler()
scaled_X=scaler.fit_transform(X)

X=pd.DataFrame(scaled_X,columns=cols)

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)

In [34]:
def model_assess(model,title):
    model.fit(X_train,y_train)
    preds=model.predict(X_test)
    print('Accuracy', title, ':', round(accuracy_score(y_test, preds), 5), '\n')

In [35]:
# Naive Bayes
nb = GaussianNB()
model_assess(nb, "Naive Bayes")

# KNN
knn = KNeighborsClassifier(n_neighbors=19)
model_assess(knn, "KNN")

# Decision trees
tree = DecisionTreeClassifier()
model_assess(tree, "Decision trees")

# Random Forest
rforest = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=0)
model_assess(rforest, "Random Forest")

# Support Vector Machine
svm = SVC(decision_function_shape="ovo")
model_assess(svm, "Support Vector Machine")

# Logistic Regression
lg = LogisticRegression()
model_assess(lg, "Logistic Regression")

Accuracy Naive Bayes : 0.29143

Accuracy KNN : 0.9001

Accuracy Decision trees : 0.81334

Accuracy Random Forest : 0.89904

Accuracy Support Vector Machine : 0.89888

Accuracy Logistic Regression : 0.89873

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,